Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Context;
using Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace GestaoRecursos.Controllers
{
    [Authorize(Roles = "Admin, Compra")]
    public class CompraController : Controller
    {
        private readonly GestaoContext _context;

        public CompraController(GestaoContext context)
        {
            _context = context;
        }

        // GET: Compra
        public async Task<IActionResult> Index()
        {
            var gestaoContext = _context.Compra.Include(c => c.Produto).Include(c => c.Fornecedor);
            return View(await gestaoContext.ToListAsync());
        }

        // GET: Compra/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compra
                .Include(c => c.Produto)
                .Include(c => c.Fornecedor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compra/Create
        public IActionResult Create()
        {
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome");
            ViewData["FornecedorId"] = new SelectList(_context.Fornecedores, "Id", "Nome").Prepend(new SelectListItem
            { 
                Text = "Selecione",
                Value = "",
                Disabled = true,
                Selected = true
            });

            return View();
        }

        // POST: Compra/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProdutoId,FornecedorId,Ativo,DataCriacao,DataAlteracao,Quantidade")] Compra compra)
        {
                compra.DataCriacao = DateTime.Now;
                compra.DataAlteracao = DateTime.Now;
                compra.Ativo = true;
                 _context.Add(compra);
                await _context.SaveChangesAsync();
               return RedirectToAction(nameof(Index));

            ViewData["FornecedorId"] = new SelectList(_context.Fornecedores, "Id", "Nome", compra.FornecedorId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome", compra.ProdutoId);

        }

        // GET: Compra/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compra.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome", compra.ProdutoId);
            ViewData["FornecedorId"] = new SelectList(_context.Fornecedores, "Id", "Nome", compra.FornecedorId);

            return View(compra);
        }

        // POST: Compra/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProdutoId,FornecedorId,Ativo,DataCriacao,DataAlteracao,Quantidade,Fornecedor")] Compra compra)
        {
            if (id != compra.Id)
            {
                return NotFound();
            }

            try
            {
                compra.DataAlteracao = DateTime.Now;
                _context.Update(compra);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CompraExists(compra.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome", compra.ProdutoId);
            ViewData["FornecedorId"] = new SelectList(_context.Fornecedores, "Id", "Nome", compra.FornecedorId);

            return RedirectToAction(nameof(Index));
        }

        // GET: Compra/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compra
                .Include(c => c.Produto)
                .Include(c => c.Fornecedor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (compra == null)
            {
                return NotFound();
            }

            ViewData["FornecedorId"] = compra.Fornecedor.Nome;
            return View(compra);
        }

        // POST: Compra/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compra = await _context.Compra.FindAsync(id);
            if (compra != null)
            {
                _context.Compra.Remove(compra);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(int id)
        {
            return _context.Compra.Any(e => e.Id == id);
        }
    }
}

Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Context;
using Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoRecursos.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        private readonly GestaoContext _context;

        public ProdutoController(GestaoContext context)
        {
            _context = context;
        }

        // GET: Produto
        public async Task<IActionResult> Index()
        {
            var gestaoContext = _context.Produtos.Include(p => p.TipoProduto);
            return View(await gestaoContext.ToListAsync());
        }

        // GET: Produto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .Include(p => p.TipoProduto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // GET: Produto/Create
        [Authorize(Roles = "Admin, Producao, Compra")]
        public IActionResult Create()
        {
            ViewData["TipoProdutoId"] = new SelectList(_context.TipoProdutos, "Id", "Nome");
            return View();
        }

        // POST: Produto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Producao, Compra")]
        public async Task<IActionResult> Create([Bind("Id,Nome,TipoProdutoId,Ativo,DataCriacao,DataAlteracao")] Produto produto)
        {
            produto.DataCriacao = DateTime.Now;
            produto.DataAlteracao = DateTime.Now;
            produto.Ativo = true;

            _context.Add(produto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            ViewData["TipoProdutoId"] = new SelectList(_context.TipoProdutos, "Id", "Nome", produto.TipoProdutoId);
            return View(produto);
        }

        // GET: Produto/Edit/5
        [Authorize(Roles = "Admin, Producao, Compra")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            ViewData["TipoProdutoId"] = new SelectList(_context.TipoProdutos, "Id", "Nome", produto.TipoProdutoId);
            return View(produto);
        }

        // POST: Produto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Producao, Compra")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,TipoProdutoId,Ativo,DataAlteracao")] Produto produto)
        {
            if (id != produto.Id)
            {
                return NotFound();
            }
            
            produto.DataAlteracao = DateTime.Now;

            try
            {
                _context.Update(produto);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProdutoExists(produto.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Produto/Delete/5
        [Authorize(Roles = "Admin, Producao, Compra")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .Include(p => p.TipoProduto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Producao, Compra")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produto = await _context.Produtos.FindAsync(id);
            if (produto != null)
            {
                _context.Produtos.Remove(produto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
            return _context.Produtos.Any(e => e.Id == id);
        }
    }
}

Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Context;
using Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoRecursos.Controllers
{
    [Authorize(Roles = "Admin, Venda")]
    public class VendaController : Controller
    {
        private readonly GestaoContext _context;

        public VendaController(GestaoContext context)
        {
            _context = context;
        }

        // GET: Venda
        public async Task<IActionResult> Index()
        {
            var gestaoContext = _context.Vendas.Include(v => v.Produto);
            return View(await gestaoContext.ToListAsync());
        }

        // GET: Venda/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Produto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // GET: Venda/Create
        public IActionResult Create()
        {
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome");
            return View();
        }

        // POST: Venda/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProdutoId,NotaFiscal,Ativo,DataCriacao,DataAlteracao,Quantidade")] Venda venda)
        {
                venda.DataCriacao = DateTime.Now;
                venda.DataAlteracao = DateTime.Now;
                venda.Ativo = true;
                _context.Add(venda);
                await _context.SaveChangesAsync();
                ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome", venda.ProdutoId);
                return RedirectToAction(nameof(Index));
        }

        // GET: Venda/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas.FindAsync(id);
            if (venda == null)
            {
                return NotFound();
            }
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome", venda.ProdutoId);

            return View(venda);
        }

        // POST: Venda/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProdutoId,NotaFiscal,Ativo,DataCriacao,DataAlteracao,Quantidade")] Venda venda)
        {
            if (id != venda.Id)
            {
                return NotFound();
            }

                try
                {
                    venda.DataAlteracao = DateTime.Now;
                    _context.Update(venda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaExists(venda.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                ViewData["ProdutoId"] = new SelectList(_context.Produtos, "Id", "Nome", venda.ProdutoId);

            return RedirectToAction(nameof(Index));
        }

        // GET: Venda/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.Produto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // POST: Venda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venda = await _context.Vendas.FindAsync(id);
            if (venda != null)
            {
                _context.Vendas.Remove(venda);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaExists(int id)
        {
            return _context.Vendas.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager


<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - GestaoRecursos</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/GestaoRecursos.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
	<header class="bg-light border-bottom">
		<div class="container-fluid d-flex justify-content-between align-items-center">
			<button class="btn btn-light mb-2 mt-2" id="sidebarToggle">
				<i class="bi bi-list"></i>
			</button>
			<div class="d-flex justify-content-center align-items-center w-100">
				<a class="navbar-brand d-flex align-items-center justify-content-center" sp-area="" asp-controller="Produto" asp-action="Index">
					<img class="w-25" src="https://private-user-images.githubusercontent.com/99574248/329904635-da5f58de-3b0b-479c-a97a-2d0111a997c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjA0NzIsIm5iZiI6MTcxOTEyMDE3MiwicGF0aCI6Ii85OTU3NDI0OC8zMjk5MDQ2MzUtZGE1ZjU4ZGUtM2IwYi00NzljLWE5N2EtMmQwMTExYTk5N2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA1MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjU2ZDBjMjg0NTQxNGFjZWU1MWIwYjI1YmRjNzZlMjA5ODUxZWRkYzg1YzMzOWE0OTUyZDljYjVlNDk4MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ozE8NjGVSAdePjBzSidmBitYt3i5TVaI9xfxUOacJpc" alt="brand logo" />
				</a>
			</div>
		</div>
	</header>

	<div class="main-content">
		<div class="sidebar bg-light border-end">
			<div class="d-flex flex-column p-lg-3 p-md-2 p-sm-0">
				<ul class="navbar-nav flex-grow-1">
					@if (SignInManager.IsSignedIn(User))
					{
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="TipoProduto"
							   asp-action="Index">
								<i class="bi bi-box link-secondary">
									<span class="txt link-secondary">Tipo de Produto</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Produto"
							   asp-action="Index">
								<i class="bg bi-box-seam link-secondary">
									<span class="txt link-secondary">Produto</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Venda"
							   asp-action="Index">
								<i class="bi bi-cart link-secondary">
									<span class="txt link-secondary">Venda</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Compra"
							   asp-action="Index">
								<i class="bi bi-basket link-secondary">
									<span class="txt link-secondary">Compra</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Relatorios"
							   asp-action="Index">
								<i class="bi bi-bar-chart link-secondary">
									<span class="txt link-secondary">Relatórios</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Usuarios"
							   asp-action="Index">
								<i class="bi bi-people link-secondary">
									<span class="txt link-secondary">Usuários</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="PerfilUsuarios"
							   asp-action="Index">
								<i class="bi bi-person-badge link-secondary">
									<span class="txt link-secondary">Perfis de usuário</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores"
							   asp-action="Index">
								<i class="bi bi-truck link-secondary">
									<span class="txt link-secondary">Fornecedores</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="ListasTecnicas"
							   asp-action="Index">
								<i class="bi bi-card-list">
									<span class="txt link-secondary">Listas Tecnicas</span>
								</i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="LancamentosProducao"
							   asp-action="Index">
								<i class="bi bi-gear">
									<span class="txt link-secondary">Lançamentos de Produção</span>
								</i>
							</a>
						</li>
						
						<div class="border-top">
						<li class="nav-item">
							<form asp-area="Identity" asp-page="/Account/Logout" method="post" id="logoutForm">
								<button type="submit" class="btn link-secondary p-0">
									<i class="bi bi-box-arrow-right"></i> Sair
								</button>
							</form>
						</li>
						</div>
					}
					else
					{
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
						</li>
					}
				</ul>
			</div>
		</div>


		<div class="content container-sm">
			<main role="main" class="pb-3">
				@RenderBody()
			</main>

			<footer class="border-top footer text-muted">
				<div class="container">
					&copy; 2024 - GestaoRecursos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
				</div>
			</footer>
		</div>

		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
		<script defer src="~/js/site.js" asp-append-version="true"></script>
		@await RenderSectionAsync("Scripts", required: false)
</body>

</html>